# Site settings
title: Dervish Moose Blog
site: Dervish Moose Blog
email: blog@dervishmoose.com
description: > # this means to ignore newlines until "baseurl:"
  I'm not a moose and I don't dance, but I do know a thing or two about tech. I love to learn and I invite you to join me in my quest to learn more about tech.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: dervishmoose
github_username:  dervishmoose

# Build settings
markdown: kramdown
